manifest:
  remotes:
    - name: vang0130
      url-base: https://github.com/vang0130
  projects:
    - name: zmk
      remote: vang0130
      revision: bongo-cat
      import: app/west.yml
  self:
    path: config
